### ISSUE TITLE
make check requires compilers

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/autoconf-feedstock#22]
should we add compilers to the build section?

**Comment by hmaarrfk** [comment]
For reference: aarch64 builds:

With compilers:
https://app.shippable.com/github/Archiconda/autoconf-feedstock/runs/6/1/console

Without compilers
https://app.shippable.com/github/Archiconda/autoconf-feedstock/runs/4/1/console
I stopped this one short because the tests take a really long time on aarch64

**Comment by ocefpaf** [comment]
Fixed in #23
